global:
  scrape_interval: 1s
  evaluation_interval: 1s
scrape_configs:
- job_name: 'flink'
  static_configs:
    - targets: 
      - 172.16.21.13:9249
- job_name: 'kafka'
  static_configs:
    - targets:
      - 172.16.21.13:8084
